FROM node:22 AS builder

WORKDIR /app
# COPY package*.json ./
COPY . .
RUN npm install
RUN npm run build

# CMD ["npm", "run", "start"]

FROM node:22 AS runner
WORKDIR /app
COPY --from=builder /app ./
EXPOSE 3000
CMD ["npm", "run", "start"]